### ISSUE TITLE
Figma - Profile Pages

### ISSUE THREAD

**Issue by Albino-Warren-BSCS32E1** [BSCS-32E1-HOSPITAL-MANAGEMENT-SYSTEM/ELEC2024_HOSPITAL_BSCS_32E1#4]
As a patient, I want a profile page where I can view and update my personal information.

**REQUIREMENTS:**

- [ ] Create wireframes for the profile page.

- [ ] Design the mockup including fields for personal information and update buttons.

**Comment by Papa-Emmanuelle-BSCS32E1** [comment]
Done!

Link:
https://www.figma.com/design/bSX7y8t0GOqOSUIEPpSGTw/Patient-Dashboard?node-id=0-1&t=IyaTVTBFuiSpJ3ZQ-1
